### GET user
GET http://localhost:3000/users/42

### GET user - fail
GET http://localhost:3000/users/myid

### POST user
POST http://localhost:3000/users?debug=true
Content-Type: application/json

{
	"first": "Firstname",
	"middle": "Middlename",
	"last": "Lastname"
}

### POST user - fail
POST http://localhost:3000/users?debug=true
Content-Type: application/json

{
	"first": "Firstname",
	"middle": 42,
	"_last": "Lastname"
}

### POST user - fail more
POST http://localhost:3000/users?debug=true&debug=0
Content-Type: application/json

{
	"first": "Firstname",
	"last": "Lastname"
}
